name: push
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "**"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Validate
        run: >
          pip install pipenv --user &&
          pipenv sync --dev &&
          pipenv run lint &&
          pipenv run test &&
          pipenv run build ${{ github.ref_name }}

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
