name: release
on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build
        run: >
          pip install pipenv --user &&
          pipenv sync --dev &&
          pipenv run build ${{ github.ref_name }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
